import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface InvoicePdfData {
  hospitalName: string;
  invoiceNo: string;
  createdAt: string;
  status: string;
  patientName: string;
  patientMrn: string;
  items: { description: string; quantity: number; unitPrice: number; amount: number }[];
  subtotal: number;
  discount: number;
  tax: number;
  total: number;
  amountPaid: number;
}

export function generateInvoicePdf(data: InvoicePdfData) {
  const doc = new jsPDF();
  const balance = data.total - data.amountPaid;

  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(data.hospitalName, 14, 20);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text('INVOICE', 196, 20, { align: 'right' });
  doc.text(data.invoiceNo, 196, 26, { align: 'right' });
  doc.text(new Date(data.createdAt).toLocaleDateString(), 196, 32, { align: 'right' });

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 36, 196, 36);

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text('Billed to:', 14, 46);
  doc.setFontSize(11);
  doc.text(data.patientName, 14, 52);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`MRN: ${data.patientMrn}`, 14, 57);

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text(`Status: ${data.status.replace('_', ' ')}`, 196, 46, { align: 'right' });

  autoTable(doc, {
    startY: 66,
    head: [['Description', 'Qty', 'Unit Price', 'Amount']],
    body: data.items.map((it) => [
      it.description,
      String(it.quantity),
      `Rs ${it.unitPrice.toLocaleString()}`,
      `Rs ${it.amount.toLocaleString()}`,
    ]),
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 9 },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const summaryX = 140;
  const summaryLines: [string, string][] = [
    ['Subtotal', `Rs ${data.subtotal.toLocaleString()}`],
    ['Discount', `-Rs ${data.discount.toLocaleString()}`],
    ['Tax', `+Rs ${data.tax.toLocaleString()}`],
    ['Total', `Rs ${data.total.toLocaleString()}`],
    ['Paid', `Rs ${data.amountPaid.toLocaleString()}`],
    ['Balance', `Rs ${balance.toLocaleString()}`],
  ];

  let y = finalY;
  doc.setFontSize(10);
  for (const [label, value] of summaryLines) {
    const isTotal = label === 'Total' || label === 'Balance';
    doc.setFont('helvetica', isTotal ? 'bold' : 'normal');
    doc.setTextColor(isTotal ? 15 : 100, isTotal ? 23 : 116, isTotal ? 42 : 139);
    doc.text(label, summaryX, y);
    doc.text(value, 196, y, { align: 'right' });
    y += 7;
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by PLYXIO HMS', 14, 285);

  doc.save(`${data.invoiceNo}.pdf`);
}
