import jsPDF from 'jspdf';
import { getImageDimensions, fitBox, detectImageFormat } from './logo-utils';

interface PayslipPdfData {
  hospitalName: string;
  hospitalLogo?: string | null;
  hospitalPhone?: string;
  hospitalEmail?: string;
  hospitalAddress?: string;
  hospitalCity?: string;
  currencySymbol: string;
  staffName: string;
  staffRole: string;
  periodLabel: string;
  compensationType: string;
  patientCount?: number;
  baseAmount: number;
  bonus: number;
  deductions: number;
  totalAmount: number;
  status: string;
  paidAt?: string | null;
}

async function buildPayslipDoc(data: PayslipPdfData): Promise<jsPDF> {
  const doc = new jsPDF();
  const currency = data.currencySymbol;

  const HEADER_TOP = 10;
  const LOGO_BOX = 20;
  let titleX = 14;

  if (data.hospitalLogo) {
    try {
      const { width, height } = await getImageDimensions(data.hospitalLogo);
      const { w, h } = fitBox(width, height, 18);
      const logoY = HEADER_TOP + (LOGO_BOX - h) / 2;
      doc.addImage(data.hospitalLogo, detectImageFormat(data.hospitalLogo), 14, logoY, w, h);
      titleX = 14 + LOGO_BOX + 4;
    } catch {
      // Malformed/unsupported image data — fall back to text-only header
    }
  }

  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(data.hospitalName, titleX, 20);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const contactLine = [data.hospitalPhone, data.hospitalEmail].filter(Boolean).join('  •  ');
  const addressLine = [data.hospitalAddress, data.hospitalCity].filter(Boolean).join(', ');
  if (contactLine) doc.text(contactLine, titleX, 26);
  if (addressLine) doc.text(addressLine, titleX, 31);

  doc.setFontSize(13);
  doc.setTextColor(100, 116, 139);
  doc.text('PAYSLIP', 196, 20, { align: 'right' });
  doc.text(data.periodLabel, 196, 26, { align: 'right' });

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 38, 196, 38);

  let y = 50;
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text(data.staffName, 14, y);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(data.staffRole.replace(/_/g, ' '), 14, y + 6);

  y += 22;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, y, 196, y);
  y += 10;

  const rows: [string, string][] = [
    [data.compensationType === 'PER_PATIENT' ? `Base Pay (${data.patientCount || 0} patients)` : 'Base Salary', `${currency} ${data.baseAmount.toLocaleString()}`],
    ['Bonus', `+${currency} ${data.bonus.toLocaleString()}`],
    ['Deductions', `-${currency} ${data.deductions.toLocaleString()}`],
  ];

  doc.setFontSize(10);
  for (const [label, value] of rows) {
    doc.setTextColor(100, 116, 139);
    doc.text(label, 14, y);
    doc.setTextColor(30, 41, 59);
    doc.text(value, 196, y, { align: 'right' });
    y += 8;
  }

  y += 2;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, y, 196, y);
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 118, 110);
  doc.text('Net Pay', 14, y);
  doc.text(`${currency} ${data.totalAmount.toLocaleString()}`, 196, y, { align: 'right' });
  doc.setFont('helvetica', 'normal');

  y += 16;
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Status: ${data.status}${data.paidAt ? ` (${new Date(data.paidAt).toLocaleDateString()})` : ''}`, 14, y);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by PLYXIO Vitals', 14, 285);

  return doc;
}

export async function generatePayslipPdf(data: PayslipPdfData) {
  const doc = await buildPayslipDoc(data);
  doc.save(`Payslip-${data.staffName.replace(/\s+/g, '-')}-${data.periodLabel.replace(/\s+/g, '-')}.pdf`);
}

export async function printPayslipPdf(data: PayslipPdfData) {
  const win = window.open('', '_blank');
  const doc = await buildPayslipDoc(data);
  const blobUrl = doc.output('bloburl');
  if (win) {
    win.location.href = blobUrl as unknown as string;
    win.addEventListener('load', () => win.print());
  }
}
