import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PrescriptionPdfData {
  hospitalName: string;
  hospitalPhone?: string;
  hospitalEmail?: string;
  hospitalAddress?: string;
  hospitalCity?: string;
  patientName: string;
  patientMrn: string;
  doctorName: string;
  doctorSpecialty?: string | null;
  date: string;
  diagnosis?: string | null;
  chiefComplaint?: string | null;
  plan?: string | null;
  items: { drugName: string; strength?: string | null; dose?: string | null; frequency?: string | null; durationDays?: number | null; quantity?: number | null; instructions?: string | null }[];
}

function buildPrescriptionDoc(data: PrescriptionPdfData): jsPDF {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(data.hospitalName, 14, 20);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const contactLine = [data.hospitalPhone, data.hospitalEmail].filter(Boolean).join('  •  ');
  const addressLine = [data.hospitalAddress, data.hospitalCity].filter(Boolean).join(', ');
  if (contactLine) doc.text(contactLine, 14, 26);
  if (addressLine) doc.text(addressLine, 14, 31);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text('PRESCRIPTION', 196, 20, { align: 'right' });
  doc.text(new Date(data.date).toLocaleDateString(), 196, 26, { align: 'right' });

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 34, 196, 34);

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text('Patient:', 14, 44);
  doc.setFontSize(11);
  doc.text(data.patientName, 40, 44);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`MRN: ${data.patientMrn}`, 40, 49);

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text('Doctor:', 120, 44);
  doc.setFontSize(11);
  doc.text(`Dr. ${data.doctorName}`, 145, 44);
  if (data.doctorSpecialty) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(data.doctorSpecialty, 145, 49);
  }

  let y = 60;
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);

  if (data.chiefComplaint) {
    doc.text('Chief Complaint:', 14, y);
    doc.setTextColor(30, 41, 59);
    const lines = doc.splitTextToSize(data.chiefComplaint, 175);
    doc.text(lines, 14, y + 5);
    y += 5 + lines.length * 5 + 4;
    doc.setTextColor(100, 116, 139);
  }

  if (data.diagnosis) {
    doc.text('Diagnosis:', 14, y);
    doc.setTextColor(30, 41, 59);
    const lines = doc.splitTextToSize(data.diagnosis, 175);
    doc.text(lines, 14, y + 5);
    y += 5 + lines.length * 5 + 4;
    doc.setTextColor(100, 116, 139);
  }

  y += 4;

  autoTable(doc, {
    startY: y,
    head: [['Medicine', 'Dose', 'Frequency', 'Duration', 'Qty', 'Instructions']],
    body: data.items.map((it) => [
      `${it.drugName}${it.strength ? ` (${it.strength})` : ''}`,
      it.dose || '—',
      it.frequency || '—',
      it.durationDays ? `${it.durationDays} days` : '—',
      it.quantity ? String(it.quantity) : '—',
      it.instructions || '—',
    ]),
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 8 },
  });

  let finalY = (doc as any).lastAutoTable.finalY + 10;

  if (data.plan) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text('Plan / Follow-up:', 14, finalY);
    doc.setTextColor(30, 41, 59);
    const lines = doc.splitTextToSize(data.plan, 175);
    doc.text(lines, 14, finalY + 5);
    finalY += 5 + lines.length * 5;
  }

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by PLYXIO Vitals', 14, 285);

  return doc;
}

export function generatePrescriptionPdf(data: PrescriptionPdfData) {
  buildPrescriptionDoc(data).save(`Prescription-${data.patientMrn}-${new Date(data.date).toISOString().slice(0, 10)}.pdf`);
}

export function printPrescriptionPdf(data: PrescriptionPdfData) {
  const doc = buildPrescriptionDoc(data);
  const blobUrl = doc.output('bloburl');
  const win = window.open(blobUrl as unknown as string, '_blank');
  win?.addEventListener('load', () => win.print());
}
